### ISSUE TITLE
Allow to choose save location

### ISSUE THREAD

**Issue by Moini** [imvenx/cssvg#2]
Hi!

I've just tried it out and it is... fascinating, especially to see how Inkscape moves along with it (and a bit frightening, too, I must admit).

One thing that confused me a lot was trying to figure out where the export file was saved. 

After spending 20minutes on searching for the result, I started to read the code. Fortunately, I was able to read it well enough to understand (from https://github.com/imvenx/cssvg/blob/0d34ede0be253d69cff733686af6c016256bcf84/src-electron/electron-main.ts#L126) that the program saves the animated SVG in ./mysvgexport ... Which is in ...  ~/bin , where the AppImage resides. And that is not where I want any exported files to live. Also, as far as I understand, they'd all have the same name, so unless I copy / move the file, the next animation will overwrite it.

Could you please add a saving dialog for the export? I find that much more important than any blur animation or rotation fixes.

**Comment by imvenx** [comment]
Hello! Thanks for your comment, I'm really happy that you liked it, and I'll put this on the top of my list to start working on it tomorrow. Actually today I finished working on an improvement related to this, now instead of using localstorage you can save/load projects directly from your filesystem, so I recomend you to download the last version, because all your old projects will be on localstorage and won't be possible to use on newer versions, unless you go to the localstorage and extract them manually or until we add an import animated svg functionality).

**Comment by imvenx** [comment]
One question, what do you mean by frightening?

**Comment by imvenx** [comment]
Done https://github.com/imvenx/cssvg/commit/c1ac9d61dbe4643310257b2474e7bb0784da012a

**Comment by Moini** [comment]
Thank you, @imvenx. Not tested yet, but it sounds really useful.

The frightening part is how things in Inkscape suddenly move around without warning :) It would be nice to write a short section about that in the README, so people know what to expect.

And how Inkscape often asks whether to reset the file, and I'm not sure what to choose, because I have not found out when and why that happens.

What I also have not understood yet: how can I move a frame along the timeline and how can I zoom out? Ctrl+Scroll did not work, and when I click on a diamond, it vanishes instead of allowing me to move it to adjust timing.

**Comment by Moini** [comment]
Oh, and how do I know which version I'm getting before downloading? On your website, it's still 0.0.1 - the same as before. Maybe as long as it's not stable you could include the commit hash in the file name or something like that? And have an 'About' or 'Info' inside so one knows which version it is?

**Comment by imvenx** [comment]
Thanks for your comments, makes a lot of sense what you said and I didn't realize this would be a problem but you are right so allow me to explain:

Q- It would be nice to write a short section about that in the README, so people know what to expect.
A- Sure, but there are also the youtube tutorials where you can see a little bit what to expect, but I'll consider adding a mini intro on the readme aswell.

Q-  how Inkscape often asks whether to reset the file, and I'm not sure what to choose, because I have not found out when and why that happens.
A- This happens because to update inkscape UI what I do is an overwrite and then a "file revert" which means you lose all the changes you did to your svg. It is a complex workaround that is not intended to be used for this purpose so is kinda tricky to explain all the implications, but basically you need to know this:
To animate: First select the time you desire, second update the svg, third save svg, fourth create keyframe
if you select the time you desire after editing the svg there are two posibilities:
- one: you didn't save the svg so it tell's you that the file is being reverted and you will lose your changes, you can press cancel and then you will update the timeline without losing your changes
- two: you did save the svg in which case it don't ask you anything, you will lose your changes as the editor goes to that timeline seocnd and refreshes the svg.

Q- how can I move a frame along the timeline and how can I zoom out? Ctrl+Scroll did not work
A- You can't atm, coming soon... altho there are workarounds but a bit complex, that involve using the mechanism of file revert explained above to conservate the state of the svg, anyways I will add this asap in the next iteration

Q- how can I move a frame along the timeline
A- shift - scroll

Q-  how can I zoom out?
A- focus on the timepicker component (the one with the timeline and the seconds) with the mouse, and ctrl + scroll 

Q-  when I click on a diamond, it vanishes instead of allowing me to move it to adjust timing.
A- xddd sorry...  since I was in a hurry and the only operation you can do is delete I just put it on first click.. soon it will be a modal or supr button

 Q- how do I know which version I'm getting before downloading
A- from now on I will start giving the project versions, you are my first user xd so didn't consider all this things to be important until now xd.

Thanks for all your feedback, If you need any help we can talk also on inkscape chat / inka discord, or here is perfect, Also you can check youtube videos to understand better the product, I will try to upload more soon.

**Comment by imvenx** [comment]
This is really usefull questions, will make a QA section with all this on the web

**Comment by imvenx** [comment]
I did an extensive tutorial with all the topics we talked and many more:
https://www.youtube.com/watch?v=vPwZxCoeH_0

**Comment by imvenx** [comment]
@Moini idk if you recieve notif if I didn't tag you so tagging you just in case.

**Comment by Moini** [comment]
Thank you for the explanations, @imvenx ! (it works without tag, too). I'm not sure I'm the first user - but probably the first one who gave feedback here after playing around with it.

Currently my headphones are charging, but I'll have a look at your video later!

Closing this report now, as the original issue has been addressed. I've set a 'watch' for your repository, so I'm going to be notified of new developments. Happy programming & animating!

**Comment by Moini** [comment]
Just watched the video - thank you, this was very well explained! 

I'd like to help you figure out which function for nodes you've been looking for, but I'm think I didn't understand yet what you wanted to do there. If you like, describe it a bit more, then I can hopefully figure it out and let you know!

Possibly... you've been looking for Alt + node dragging? To move multiple selected nodes more organically? Or did you just want to hide the handles visually?

**Comment by imvenx** [comment]
Is just to hide the angles nodes since is annoying, and you always missclick them instead of the node itself, but I have done it in my main pc is just that I didn't remember there. The idea in the future would be to gather all this settings and make a "inka" inkscape profile to animate that defaults to that (there are many others) so it improves a little bit the ux. But that's too far yet xd I think the new version of inka is broken for ubuntu I was trying to test it and I can't make it work.. on linux mint all is way easier. The thing is that you need to  have inkscape as your default program to open svg's and in ubuntu is quite a trip to do that :/ so im not sure if is working xd, so GL xd, idk if you use ubuntu or mint but a workaround to this would be to open the file manually  /tmp/cssvg/temp.svg with inkscape (This is a thing I did so now I use inkscape as a canvas and user can switch from one project to another and inkscape will still update, and I dont rewrite any important file)

**Comment by Moini** [comment]
Using LM with Inkscape from ppa, no problems so far. 

Maybe it's the snap that you're using on Ubuntu. To check do 
$ snap list

Remove the snap, install ppa version.

![Disable node handles](https://user-images.githubusercontent.com/3240233/204101366-8a8fcb36-176e-47ca-8c9d-59c56df67eca.gif)

You can also open the preferences and search for 'handle' (in English... you speak … Spanish, maybe? Don't know what their name is in Spanish...) - maybe even changing the size is enough.

**Comment by imvenx** [comment]
cool! that's it
